### ISSUE TITLE
Wrong Murmurhash64B()

### ISSUE THREAD

**Issue by sko00o** [rryqszq4/go-murmurhash#2]
Maybe typo [this line](https://github.com/rryqszq4/go-murmurhash/blob/master/murmurhash2.go#L128). 

Fix it：

```go
h2 *= m; h2 ^= k2
```

**Comment by rryqszq4** [comment]
> Maybe typo [this line](https://github.com/rryqszq4/go-murmurhash/blob/master/murmurhash2.go#L128).
> 
> Fix it：
> 
> ```go
> h2 *= m; h2 ^= k2
> ```

Thanks for your review and already fixed.

**Comment by sko00o** [comment]
Missing following code [here](https://github.com/rryqszq4/go-murmurhash/blob/master/murmurhash2.go#L137).

```go
data = data[4:]
```

**Comment by rryqszq4** [comment]
> Missing following code [here](https://github.com/rryqszq4/go-murmurhash/blob/master/murmurhash2.go#L137).
> 
> ```go
> data = data[4:]
> ```

Fixed it and you maybe try to review.
